import { Search, BarChart4, Database, Cpu, Award, FileText, Briefcase, ShieldCheck, GraduationCap, Heart, Terminal, Activity } from 'lucide-react';

export const MODES = {
  ON_CHAIN: 'ON-CHAIN',
  ANALYTICS: 'ANALYTICS',
  AGENTIC: 'AGENTIC'
};

export const CONTENT_MATRIX = {
  [MODES.ON_CHAIN]: {
    hero: "Interrogating on-chain shards for governance integrity.",
    projects: [
      { id: "WF-25", title: "Wavefront", category: "Market Intelligence", description: "Onchain market intelligence for Solana, featuring narrative clustering, risk scoring, and AI-powered token analysis in one terminal. Powered by Birdeye data and Gemini AI.", tags: ["Solana", "AI", "Intelligence", "Birdeye"], icon: 'Activity', link: 'https://wavefront-gray.vercel.app', thumbnail: '/thumbnails/wavefront.png' },
      { id: "SB-25", title: "Sunboard 🌅", category: "DeFi Intelligence", description: "Advanced Sunrise Intelligence Terminal for Solana. Momentum scoring, holder distribution, and real-time liquidity tracking for high-conviction assets.", tags: ["Solana", "DeFi", "Analytics"], icon: 'Terminal', link: 'https://sunboard.vercel.app', thumbnail: '/thumbnails/sunboard.png' },
      { id: "VX-25", title: "Vertex ⚡", category: "Solana Invoicing", description: "Institutional-grade invoicing tool for the Solana freelance economy. Generate smart agreements and get paid in USDC/SOL instantly.", tags: ["Solana", "Invoicing", "Fintech"], icon: 'ShieldCheck', link: 'https://vertex-pay.vercel.app', thumbnail: '/thumbnails/vertex.png' },
      { id: "ST-01", title: "Superteam Earn Wins", category: "Proof of Work", description: "8 Competitive Bounty Wins in technical research and on-chain analysis.", tags: ["Superteam", "Wins"], icon: 'Award', link: 'https://superteam.fun/earn/t/Ghostiemoh', thumbnail: '/thumbnails/superteam.png' },
      { id: "MD-03", title: "MetaDao Analysis", category: "Governance Data", description: "Analyzing governance participation and vote weight distribution within MetaDao.", tags: ["DAO", "Governance"], icon: 'Database', link: 'https://docs.google.com/document/d/1HTd4yvNuGfzq1s_K62YRKFgCPEta__THQPxuwPHXSCg/edit?usp=sharing', thumbnail: '/thumbnails/metadao.png' },
      { id: "KV-03", title: "Kelsier Ventures Analysis", category: "Venture Analytics", description: "Analyzing wallet movements and venture capital flow within private investment networks.", tags: ["VC", "On-chain"], icon: 'Database', link: 'https://docs.google.com/document/d/1SDxOn-GqTk7od60YsqBVENOSMm_nVDR9oxxDlDWfzKY/edit?usp=sharing', thumbnail: '/thumbnails/kelsier.png' },
      { id: "SD-01", title: "Solana Fraud Detection", category: "Forensics", description: "Forensic analysis of fraudulent activities on the Solana network.", tags: ["Forensics", "Solana"], icon: 'Search', link: 'https://docs.google.com/document/d/1pxf4EtWhSU6DWerlkD1fG8HMcj1QWlvBH3YYWmuYbec/edit?usp=sharing', thumbnail: '/thumbnails/fraud-detection.png' }
    ]
  },
  [MODES.ANALYTICS]: {
    hero: "Advanced Data Engineering & Mathematical Rigor.",
    projects: [
      { id: "DL-01", title: "Data Cleaning Pipeline", category: "Excel Preprocessing", description: "Standardized, cleaned, and parsed 1,200 transaction records in Excel. Audited key integrity constraints, imputed 309 missing coupon codes, ran format normalization, and converted data range to filterable Excel Tables.", tags: ["Excel", "Data Cleaning", "Data Preparation"], icon: 'Database', link: 'https://github.com/Ghostiemoh/decodelabs-internship-project-1', thumbnail: '/thumbnails/decodelabs-1.png' },
      { id: "DL-02", title: "Executive Dashboard", category: "Excel Analytics", description: "Built a dynamic, formula-driven financial dashboard. Used AVERAGE, SUMIF, and COUNTIFS to aggregate sales metrics, yearly trends, acquisition performance, and coupon code return rates.", tags: ["Excel", "Dashboards", "Business Intelligence"], icon: 'BarChart4', link: 'https://github.com/Ghostiemoh/decodelabs-internship-project-2', thumbnail: '/thumbnails/decodelabs-2.png' },
      { id: "DL-03", title: "Database Querying & Insights", category: "SQL Database Insights", description: "Constructed database schemas and wrote query scripts to profile sales metrics. Aggregated monthly seasonality, mapped the logistics funnel, ran YoY H1 trends, and audited coupon return rates.", tags: ["SQL", "Querying", "Database Analytics"], icon: 'Terminal', link: 'https://github.com/Ghostiemoh/decodelabs-internship-project-3', thumbnail: '/thumbnails/decodelabs-3.png' },
      { id: "NH-04", title: "Nashville Housing Data", category: "SQL Data Cleaning", description: "Cleaned and standardized 56,000+ real-estate records in SQL by handling null values, removing duplicates, normalizing address fields, and using BULK INSERT for efficient loading.", tags: ["SQL", "Data Cleaning", "BULK INSERT"], icon: 'Database', link: '/legacy/projects/2.txt', thumbnail: '/thumbnails/nashville.png' },
      { id: "CO-05", title: "COVID-19 Data Exploration", category: "SQL Analytics", description: "Explored global infection and vaccination trends across countries with advanced SQL using CTEs, window functions, and type conversions. Built views surfacing death rates, infection spikes, and vaccination-to-case correlations.", tags: ["SQL", "CTEs", "Views"], icon: 'BarChart4', link: '/legacy/projects/1.txt', thumbnail: '/thumbnails/covid.png' },
      { id: "BS-06", title: "Bicycle Sales Performance", category: "Excel BI", description: "In-depth analysis of 100,000+ retail transactions across age, gender, and region in Excel. Interactive PivotTable dashboards and heatmaps; pricing recommendations drove a 12% profitability lift in Q2 2024.", tags: ["Excel", "Pivot Tables", "Sales"], icon: 'BarChart4', view: '/projects/bike-sales.xlsx', download: '/projects/bike-sales.xlsx', thumbnail: '/thumbnails/bike-sales.png' },
      { id: "CL-11", title: "Call List Analysis", category: "Excel Analytics", description: "Analyzed 5,000+ customer call logs in Excel to surface service gaps, uncovering $250k+ in missed opportunities. Dynamic pivot dashboards with recurring reports automated via macros.", tags: ["Excel", "Pivot Tables", "Macros"], icon: 'BarChart4', view: '/projects/call-center-analysis.xlsx', download: '/projects/call-center-analysis.xlsx', thumbnail: '/thumbnails/call-center.png' },
      { id: "CF-07", title: "Coffee Shop Sales Dashboard", category: "Excel BI", description: "Interactive Excel dashboard analyzing coffee-shop transactions by store location, product, and time. PivotTable engine with slicers for dynamic store-level performance drill-down.", tags: ["Excel", "Pivot Tables", "Retail"], icon: 'BarChart4', view: '/projects/coffee-shop-sales.xlsx', download: '/projects/coffee-shop-sales.xlsx', thumbnail: '/thumbnails/coffee-shop.png' },
      { id: "RS-08", title: "Retail Sales Dashboard", category: "Excel BI", description: "Dynamic Excel sales dashboard with slicers for age group, country, gender, product category, and year to surface revenue trends and customer segments across the full product range.", tags: ["Excel", "Slicers", "Dashboard"], icon: 'BarChart4', view: '/projects/retail-sales-dashboard.xlsx', download: '/projects/retail-sales-dashboard.xlsx', thumbnail: '/thumbnails/retail-sales.png' },
      { id: "PB-09", title: "Apocalypse Food Prep", category: "Power BI", description: "Interactive Power BI report modelling survival food-prep inventory, built with Power Query, DAX measures, relationships, and drill-down visuals. View the PDF, or download the .pbix to open the live model in Power BI Desktop.", tags: ["Power BI", "DAX", "Power Query"], icon: 'Activity', view: '/projects/apocalypse-dashboard.pdf', download: '/projects/apocalypse-dashboard.pbix', thumbnail: '/thumbnails/apocalypse.png' },
      { id: "LS-25", title: "LedgerSnap", category: "Financial Architecture", description: "High-fidelity financial archival system. Transforming chaotic spending into a streamlined digital ledger with deep analytical insights.", tags: ["Finance", "Archival", "UX"], icon: 'Database', link: 'https://ledgersnap-one.vercel.app', thumbnail: '/thumbnails/ledgersnap.png' },
      { id: "DA-30", title: "30-Day Data Architect Challenge", category: "Educational Series", description: "Intensive masterclass transitioning from manual data cleaning to building scalable data systems and on-chain intelligence.", tags: ["SQL", "Excel", "Architecture"], icon: 'GraduationCap', link: 'https://github.com/Ghostiemoh/Excel_SQL_Mastery_Template', thumbnail: '/thumbnails/da-30.png' }
    ]
  },
  [MODES.AGENTIC]: {
    hero: "Synthesizing intelligence through protocol research.",
    projects: [
      { id: "TR-07", title: "Trepa Prediction", category: "Predictive Analytics", description: "A precision prediction platform focusing on data accuracy and market sentiment analysis.", tags: ["Prediction", "Web3"], icon: 'Search', link: 'https://github.com/Ghostiemoh', thumbnail: '/thumbnails/trepa.png' },
      { id: "SR-10", title: "Switchboard Research", category: "Oracle Intelligence", description: "Deep research into decentralized oracle networks and data feed reliability.", tags: ["Oracles", "Research"], icon: 'Search', link: 'https://github.com/Ghostiemoh', thumbnail: '/thumbnails/switchboard.png' },
      { id: "MA-02", title: "MarginFi Protocol Analytics", category: "Protocol Intel", description: "In-depth research into borrowing, lending, and yield strategies within the MarginFi ecosystem.", tags: ["DeFi", "MarginFi"], icon: 'BarChart4', link: 'https://docs.google.com/document/d/1HTd4yvNuGfzq1s_K62YRKFgCPEta__THQPxuwPHXSCg/edit?usp=sharing', thumbnail: '/thumbnails/marginfi.png' },
      { id: "SE-09", title: "Sanafi Ethical Infographic", category: "Data Ethics", description: "An ethical exploration into data privacy and infographic systems.", tags: ["Ethics", "Data"], icon: 'Search', link: 'https://github.com/Ghostiemoh', thumbnail: '/thumbnails/sanafi.png' }
    ]
  }
};
